
```{r, env, message=FALSE, echo=FALSE, cache=FALSE, warning=FALSE}
library("vp.misc")
suppressPackageStartupMessages(library("MSnbase"))
```

```{r core, fig.align='center', fig.height=8, fig.width=8}
data(srm_msnset)

linkage = 'ward.D'
hclustfun=function(x,...)
   hclust(x, method=linkage,...)

pearson.dist <- function(x){
   corMat <- (1-cor( t(x), 
                     method="pearson",
                     use="pairwise.complete.obs" ))/2
   corMat[is.na(corMat)] <- mean(corMat, na.rm=T)
   return(as.dist(corMat))}

eucl.dist <- function(x){
   distMat <- dist(x)
   distMat[is.na(distMat)] <- mean(distMat, na.rm=T)
   return(as.dist(distMat))}

# match.group, subject.type, msex, Visible blood contamination
columnCol <- pData(msnset)[,c("subject.type", "match.group", "msex", 
                              "Visible blood contamination")]
columnCol <- as.data.frame(lapply(columnCol, as.factor))
columnCol$subject.type <- 
    c('red','orange','blue')[columnCol$subject.type]
columnCol$match.group <- 
    jet.colors(nlevels(columnCol$match.group))[columnCol$match.group]
columnCol$msex <- 
    c('pink','olivedrab')[columnCol$msex]
columnCol$Visible.blood.contamination <- 
    c('black','lightgrey')[columnCol$Visible.blood.contamination]

heatmap.plus.2(exprs(msnset), 
               hclustfun = hclustfun,
               dist = pearson.dist,
               propColSide=0.1,
               scale="none",
               ColSideColors=as.matrix(columnCol),
               breaks=c(-4,seq(-2,+2,length=100),+4),
               col=gplots::bluered(102-1)
               )
```

<!--
```{r si}
sessionInfo()
```
-->
